
---
title: "FPT"
author: "Grant Poulsen, Claire Plunkett, Jody Reimer"
date: "10/03/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

Purpose: Simulation solutions to the SDE and find the FPT of each one. Save as
a vector. The histogram of these values can then be compared to the pdf found 
using the backward Komogorov approach. 

Run Time: 30 Minutes

```{r library, message = F}
start.time <- Sys.time()
###Setup###
library(sde)
library(ggplot2)
library(R.matlab)
```


```{r}
###Import pdf data from FPT.mlx & plot it###
#t <- seq(0,4500,length=100)	
#pdf <- unlist(readMat('pdf.mat'))
#tval <- unlist(readMat('t.mat'))
#plot(tval, pdf, type = 'l')
```


```{r}

###Gather statistical data on FPT for model###

#Parameters
r <- .05
K <- 2
a <- .023
h <- .38
q <- 5
sigmaVal <- .02

numsims = 10000 # number of stochastic simulations
simLength <- 5000 # length of stochastic simulations
xinit <- 0.3 # initial condition
threshold <- 0.9798 # if a=0.023 (ghost case), threshold for FPT is 0.9798

#Define drift and diffusion vectors
mu <- expression(r*x*(1-(x/K)) - (a*x^5)/(x^5 + h^5))
dif <- expression(sigmaVal*x)

#Vector to collect first passage times
fpt <- vector(length = numsims, mode = "numeric")

#Find FPT for each simulation
for(i in 1:numsims){
 print(i)
 #Simulate the SDE
 X <- sde.sim(t0 = 0,T = simLength,X0 = xinit,N = simLength, drift = mu, sigma = dif, sigma.x = sigmaVal)
 fpt[i] <- min(which(X > threshold))
}

write.table(fpt,file="simulatedFPTS.csv",sep=",",col.names =FALSE,row.names=FALSE)
```


```{r}
###Plot pdf over Histogram Data###
histogram <- hist(fpt, 
                  main = '',
                  xlab = "T_escape", 
                  border = "Blue", 
                  col = "Orange", 
                  cex.axis = 1.48,
                  cex.lab = 1.48,
                  breaks = 22,
                  freq = FALSE)

end.time <- Sys.time()
time.taken <- round(end.time - start.time,2)
time.taken
# par(new=TRUE)
# 
# plt <- plot(tval, pdf, type = 'l', axes = FALSE, ylab = '', xlab = '', lwd = 2.0, col = 'blue')

```